# Generated by Django 6.0.7 on 2026-07-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_id',
        ),
    ]
